### ISSUE TITLE
Use BannerClick as an extension

### ISSUE THREAD

**Issue by intumwa** [bannerclick/bannerclick#4]
Hello, I wonder, have you thought of building a browser extension? That way BannerClick could be used beyond OpenWPM in other browser instrumentation tools such as Puppeteer and Playwright.

**Comment by GorgMish** [comment]
Hello,
That is an interesting question. Actually, recently we started a new project in which we plan to implement a similar version of BannerClick as an extension.

**Comment by ghost** [comment]
Hi @GorgMish, I am currently considering using something like Bannerclick for my Master thesis. Since I want to use Playwright, a Browser Extension with Bannerclick's  functionality would be really useful. Is the project you mentioned already finished?

**Comment by GorgMish** [comment]
Hi, we have implemented a browser extension similar to BannerClick, but it still needs to be tested. Which BannerClick functionality do you need currently?

**Comment by ghost** [comment]
I would be happy to test it with my usecase and provide you with the results if you want. My playwright crawler visits a website, collects some data (cookies, local storage), should then click on "accept all" (or anything similar) and then collect again some data. Is this something which is achievable? It would also be enough if I could assemble based on your code some JS code, which I can  execute in the browser to click on accept.

**Comment by GorgMish** [comment]
The "accept" functionality has not been tested yet on a large scale. We will publish it as soon as it is complete.

**Comment by ghost** [comment]
Hi @GorgMish ,
I wanted to check in and kindly ask if there have been any updates regarding the accept functionality. I am open to assist in testing if needed.

**Comment by GorgMish** [comment]
Hi Matthias,

We have stopped working on the extension since we started on another idea.
Moreover, the student who were responsible for that is not working with us
any more.
Nevertheless the implementation of the extension especially just accept
part shouldn’t be that much tricky. So if you really need that I suggest go
ahead and implement it. If you want to use the same approach as BannerClick
feel free to reach me out if you have questions.

Best regards,
Ali
